In [2]:
import pandas as pd

In [10]:
pd.read_csv("data/imagefeedback.csv").head()

,Unnamed: 0,ID,CREATEDBY,CREATEDON,IMAGE_ID,SEGMENTATION_ID,DONE,studyFeedback_id,frame,SIDE
0,0,000cc8ba-e751-4373-87e6-c344cabb7dae,lekandnow@gmail.com,2023-06-17 19:04,131aedfhs6pnf1fvtvp49mk5l3gmfzrq22,000cc8ba-e751-4373-87e6-c344cabb7dae,0,90aae3e4-ff1f-44bb-bd86-407829eeaaa6,22,1.0
1,1,00378b08-8a66-4892-87c6-a8d4c9ab8c3b,lekandnow@gmail.com,2023-05-14 20:03,131aedfhs6pnf1fvtvp49mff2plx3rdw22,00378b08-8a66-4892-87c6-a8d4c9ab8c3b,0,aad9f64b-69f6-4c59-9294-aa24c57f3c48,21,1.0
2,2,007d494a-abbc-454e-8bca-b56267537310,lekandnow@gmail.com,2023-06-17 19:37,131aedfhs6pnf1fvtvp49mk5xd63iqs422,007d494a-abbc-454e-8bca-b56267537310,0,71612628-c1b7-4eba-9922-286ec2546af9,41,0.0
3,3,009b6b0c-dc60-4d13-a929-9928ae987adc,sgurba@gmail.com,2023-04-28 22:48,131aedfhs6pnf1fvtvp49mg85r5ebddd22,009b6b0c-dc60-4d13-a929-9928ae987adc,0,e02b2f59-77be-4216-8e25-cdd09609261b,30,0.0
4,4,00c2967a-724b-4f95-8bd2-2f10736c9786,lekandnow@gmail.com,2023-12-30 07:35,13c2ur5452xb62wphb959tewknprp1b4,00c2967a-724b-4f95-8bd2-2f10736c9786,0,c464a1f8-25dc-41ef-ae74-b83c012da32c,28,0.0

In [9]:
pd.read_csv("data/imagerejectionfeedback.csv").head()

,Unnamed: 0,ID,IMAGE_ID,TECHNICALVESSELSNOTVISIBLE,TECHNICALVESSELSOVERLAP,TECHNICALNOCONTRAST,TECHNICALLOWQUALITY,PROCEDURALFEMORALACCESS,PROCEDURALELECTRODESVISIBLE,PROCEDURALCATHETERINAORTA,EXAMINATIONAORTOGRAPHY,EXAMINATIONVENTRICULOGRAPHY,PHYSIOLOGICALCRITICALSTENOSIS,PHYSIOLOGICALCOLLATERALCIRCULATION,COMMENT,CREATEDBY,CREATEDON
0,0,0005958b-4ec8-4f20-b458-f4d70019d50f,131aedfhs6pnf1fvtvp49mn62i343cqe22,0,0,0,0,0,0,0,0,0,0,0,NaN,barteknawrotek@gmail.com,2023-01-06 15:28
1,1,03a37bb4-57c5-4b2a-a3f9-088499276bec,13c2ur549vohc0jat2wd23me01,0,1,0,0,0,0,0,0,0,0,0,NaN,barteknawrotek@gmail.com,2023-01-02 10:46
2,2,1084bb55-e5f7-4598-8c76-f9482f8ef950,13c2ur549vohc0jat2e6x42wuf2,0,1,0,0,0,0,0,0,0,0,0,NaN,barteknawrotek@gmail.com,2023-01-01 14:17
3,3,1203b030-e721-4b20-bef5-1916de8ace18,13c2ur549vohc0jat2dfo3qgjj1,0,0,0,0,0,0,0,0,0,0,0,NaN,barteknawrotek@gmail.com,2022-12-12 19:11
4,4,18945bdf-dc16-4e34-ae42-fbd63051c23a,131aedfhs6pnf1fvtvp49mn6qbqhytn9222,0,0,0,0,0,0,0,0,0,0,0,NaN,barteknawrotek@gmail.com,2023-01-06 15:29

In [8]:
pd.read_csv("data/image.csv").head()

,Unnamed: 0,ID,ACQUISITIONDATE,ACQUISITIONNO,ACQUISITIONUID,AGE,BATCH,BODYPARTEXAMINED,DATASET,FRAMERATE,...,POSITIONERSECONDARYANGLEFRAMEOFFSET,REPRESENTATIVEFRAME,SERIESDESCRIPTION,SERIESINSTANCEUID,SERIESNO,SEX,STUDYDESCRIPTION,STUDYINSTANCEUID,URL,STUDY_ID
0,0,12aw4ack71831bocuf5j3gru5yyhiw383xp,20220209.0,NaN,NaN,069Y,modified,NaN,Ukraine,0,...,[],33,NaN,1.2.392.200036.9116.3.1.19612167.2022020913050...,2,M,NaN,1.2.392.200036.9116.3.1.19612167.2022020912402...,Ukraine/modified/p1s2.dcm,1.2.392.200036.9116.3.1.19612167.2022020912402...
1,1,12aw4ack71831bocuf5j3gru620taw793ic,20220209.0,NaN,NaN,069Y,modified,NaN,Ukraine,0,...,[],28,NaN,1.2.392.200036.9116.3.1.19612167.2022020913064...,3,M,NaN,1.2.392.200036.9116.3.1.19612167.2022020912402...,Ukraine/modified/p1s3.dcm,1.2.392.200036.9116.3.1.19612167.2022020912402...
2,2,12aw4ack71831bocuf5j3gru6xjx2wb63kf,20220209.0,NaN,NaN,069Y,modified,NaN,Ukraine,0,...,[],43,NaN,1.2.392.200036.9116.3.1.19612167.2022020913211...,4,M,NaN,1.2.392.200036.9116.3.1.19612167.2022020912402...,Ukraine/modified/p1s4.dcm,1.2.392.200036.9116.3.1.19612167.2022020912402...
3,3,12aw4ack71831bocuf5j3gru87hd5wv74yv,20220209.0,NaN,NaN,069Y,modified,NaN,Ukraine,0,...,[],28,NaN,1.2.392.200036.9116.3.1.19612167.2022020913425...,9,M,NaN,1.2.392.200036.9116.3.1.19612167.2022020912402...,Ukraine/modified/p1s9.dcm,1.2.392.200036.9116.3.1.19612167.2022020912402...
4,4,12aw4ack71831bocuf5j3gru893y5wz22kb,20220209.0,NaN,NaN,069Y,modified,NaN,Ukraine,0,...,[],20,NaN,1.2.392.200036.9116.3.1.19612167.2022020913433...,10,M,NaN,1.2.392.200036.9116.3.1.19612167.2022020912402...,Ukraine/modified/p1s10.dcm,1.2.392.200036.9116.3.1.19612167.2022020912402...

In [6]:
pd.read_csv("data/studyrejectionfeedback.csv").head()

,Unnamed: 0,ID,STUDY_ID,CAUSEBYPASSPRESENT,CAUSESTENTPRESENT,CAUSEMYOCARDIALINFARCTION,CAUSEWRONGBODYPART,CAUSELITTLEDATA,CAUSELOWQUALITY,CAUSECRITICALSTENOSIS,CAUSECOLLATERALCIRCULATION,CAUSEFEMORALACCESS,COMMENT,CREATEDBY,CREATEDON
0,0,004ee057-321a-43aa-8a55-b87cf3997ed9,1.3.46.670589.28.68172260235162120220310122647...,0,0,0,0,0,0,0,0,0,"tylko swing lca, rca",zamiedzaidalej@gmail.com,2023-03-22 04:50:04
1,1,00aefb36-3128-4142-a91e-cb0ac20e2a7a,1.3.46.670589.28.68172260235162120220311100836...,0,0,0,0,0,0,0,0,0,brak RCA,zamiedzaidalej@gmail.com,2023-03-22 04:51:29
2,2,00b8057a-2d38-4cb0-9815-7706dec6af25,1.3.46.670589.28.68172260235162120220505111712...,0,1,0,0,0,0,0,0,0,NaN,zamiedzaidalej@gmail.com,2023-06-04 03:55:38
3,3,01173c36-81cc-4545-96b8-8f7e8e40a153,1.3.46.670589.28.68172260235162120220131112046...,0,0,0,0,0,0,0,0,0,brak RCA,zamiedzaidalej@gmail.com,2023-03-18 01:46:46
4,4,012667bd-d9bd-47c4-a987-2eebda79b7af,1.3.46.670589.28.68172260235162120220117141649...,0,0,0,0,0,0,0,0,0,"swing lca, rca - statyczne ale czy diagnostycz...",zamiedzaidalej@gmail.com,2023-03-15 23:55:46

In [7]:
pd.read_csv("data/study.csv").head()

,Unnamed: 0,ID,BATCH,COMMENT,DATASET,DOMINANCE,PATIENT,STUDYDESCRIPTION,SYNTAXSCORE,TECHNICALREVIEW
0,0,1.2.392.200036.9116.3.1.19612167.2022020912402...,NaN,NaN,NaN,NaN,Greggory Edson,NaN,0,0
1,1,1.2.392.200036.9116.3.1.19612167.2022080510441...,NaN,NaN,NaN,NaN,Delmar Sampe,NaN,0,0
2,2,1.2.392.200036.9116.3.1.19612167.2022093012183...,NaN,"złe badanie, tylko jedna projekcja",NaN,1.0,Kerel Columber,NaN,2,0
3,3,1.2.840.113619.2.409.65140653521484606129.1657...,NaN,NaN,NaN,NaN,Jarae Bottles,NaN,0,0
4,4,1.2.840.113619.2.409.65140653521484606129.1657...,NaN,NaN,NaN,NaN,Wilber Sparhawk,NaN,0,0

In [11]:
pd.read_csv("data/framerejectionfeedback.csv").head()

,Unnamed: 0,"ID,IMAGE_ID,REJECTEDFRAME,SELECTEDFRAME,CAUSESEPARATION,CAUSEDEPICTION,CAUSECONTRAST,CAUSEQUALITY,COMMENT,CREATEDBY,CREATEDON"
0,0,"000cc8ba-e751-4373-87e6-c344cabb7dae,131aedfhs..."
1,1,"00378b08-8a66-4892-87c6-a8d4c9ab8c3b,131aedfhs..."
2,2,"007d494a-abbc-454e-8bca-b56267537310,131aedfhs..."
3,3,"009b6b0c-dc60-4d13-a929-9928ae987adc,131aedfhs..."
4,4,"00d4d0c1-1b5d-49a8-8c18-3eeaf2ef6d70,131aedfhs..."

---

In [12]:
pd.read_csv("data/series_selection_accepted.csv", sep=";").head()

,ID,CREATEDBY,CREATEDON,IMAGE_ID,SEGMENTATION_ID,DONE,studyFeedback_id,frame,SIDE
0,000cc8ba-e751-4373-87e6-c344cabb7dae,lekandnow@gmail.com,2023-06-17 19:04,131aedfhs6pnf1fvtvp49mk5l3gmfzrq22,000cc8ba-e751-4373-87e6-c344cabb7dae,0,90aae3e4-ff1f-44bb-bd86-407829eeaaa6,22,1.0
1,00378b08-8a66-4892-87c6-a8d4c9ab8c3b,lekandnow@gmail.com,2023-05-14 20:03,131aedfhs6pnf1fvtvp49mff2plx3rdw22,00378b08-8a66-4892-87c6-a8d4c9ab8c3b,0,aad9f64b-69f6-4c59-9294-aa24c57f3c48,21,1.0
2,007d494a-abbc-454e-8bca-b56267537310,lekandnow@gmail.com,2023-06-17 19:37,131aedfhs6pnf1fvtvp49mk5xd63iqs422,007d494a-abbc-454e-8bca-b56267537310,0,71612628-c1b7-4eba-9922-286ec2546af9,41,0.0
3,009b6b0c-dc60-4d13-a929-9928ae987adc,sgurba@gmail.com,2023-04-28 22:48,131aedfhs6pnf1fvtvp49mg85r5ebddd22,009b6b0c-dc60-4d13-a929-9928ae987adc,0,e02b2f59-77be-4216-8e25-cdd09609261b,30,0.0
4,00af090a-c8e6-4b96-af3c-fcd304ef4f24,barteknawrotek@gmail.com,2023-01-01 14:17,13c2ur549vohc0jat2e6y42x3z1,00af090a-c8e6-4b96-af3c-fcd304ef4f24,0,7984cce0-0547-4da5-b839-70ed4d639305,33,NaN

In [9]:
pd.read_csv("data/series_selection_rejected.csv", sep=";").head()

,ID,IMAGE_ID,TECHNICALVESSELSNOTVISIBLE,TECHNICALVESSELSOVERLAP,TECHNICALNOCONTRAST,TECHNICALLOWQUALITY,PROCEDURALFEMORALACCESS,PROCEDURALELECTRODESVISIBLE,PROCEDURALCATHETERINAORTA,EXAMINATIONAORTOGRAPHY,EXAMINATIONVENTRICULOGRAPHY,PHYSIOLOGICALCRITICALSTENOSIS,PHYSIOLOGICALCOLLATERALCIRCULATION,COMMENT,CREATEDBY,CREATEDON
0,0005958b-4ec8-4f20-b458-f4d70019d50f,131aedfhs6pnf1fvtvp49mn62i343cqe22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,barteknawrotek@gmail.com,2023-01-06 15:28
1,03a37bb4-57c5-4b2a-a3f9-088499276bec,13c2ur549vohc0jat2wd23me01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,barteknawrotek@gmail.com,2023-01-02 10:46
2,1084bb55-e5f7-4598-8c76-f9482f8ef950,13c2ur549vohc0jat2e6x42wuf2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,barteknawrotek@gmail.com,2023-01-01 14:17
3,1203b030-e721-4b20-bef5-1916de8ace18,13c2ur549vohc0jat2dfo3qgjj1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,barteknawrotek@gmail.com,2022-12-12 19:11
4,18945bdf-dc16-4e34-ae42-fbd63051c23a,131aedfhs6pnf1fvtvp49mn6qbqhytn9222,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,barteknawrotek@gmail.com,2023-01-06 15:29

In [13]:
pd.read_csv("data/frame_selection.csv").head()

,tag_id,image_id,frame,segmentation,timestamp,user
0,84f6ac8a-39b8-46a0-9572-432ab85dffb4,131aedfhs6pnf1fvtvp49mjf02x1fl1f22,38,eJztne1is7YSBkmcvE7u/4bb2E5sQEK7Qrta0MyfnmAM6p...,2024-01-24 16:02:32.568104,lekandnow@gmail.com
1,4f573378-1388-46de-951b-95f1e44d390e,131aedfhs6pnf1fvtvp49mjf04wc7y5722,23,eJztnel6o7oSALmZLJ73f+FznWQSQFu31C2EVPVrYrPNV4...,2024-01-24 16:02:32.638365,lekandnow@gmail.com
2,09d328c9-8b75-464e-a68d-f30dd9db2499,131aedfhs6pnf1fvtvp49mjf04y0vtqu22,36,eJztnel2o7gWRulyust5/xe+1xlsBknoTBrM3j96pYMBZe...,2024-01-24 16:02:32.616167,lekandnow@gmail.com
3,b83370d1-4bbb-44f5-ad75-8f8f6b572836,131aedfhs6pnf1fvtvp49mk5l3qcg5hh22,18,eJztne1im7oSAJWe49O67//A9+LEtgAB+tjVrqyZP20dG0...,2024-01-24 16:13:02.512389,lekandnow@gmail.com
4,222454ee-2b93-4854-ad91-5d37147ac04e,131aedfhs6pnf1fvtvp49mk5l3ra0gpr22,21,eJztnVl2pDgQAHGX7Zmu+x94pnZAW0ogKaWM+GvbDfhFlA...,2024-01-24 16:13:02.879827,lekandnow@gmail.com